### ISSUE TITLE
About CAbicgstab.m

### ISSUE THREAD

**Issue by Rushsurf** [eccarson/ca-ksms#1]
I TRY TO USE CAbicgstab.m:
[CABICGSTAB_example.txt](https://github.com/eccarson/ca-ksms/files/2401619/CABICGSTAB_example.txt)
The result is not correct,i don't know why?
![image](https://user-images.githubusercontent.com/32186238/45823938-6ae89d00-bd21-11e8-9654-0a3587a54fa9.png)

**Comment by eccarson** [comment]
Hello,
I believe this issue has been fixed. Please try again with the new code. 
The issue was that the inner products involving the "shadow residual" (rt0 in the code) were the complex conjugates of what they should have been. The code was not well-tested in the case where complex vectors occur - I apologize!

**Comment by Rushsurf** [comment]
Thanks a lot !This issue has been fixed ,the answer is right...
And I have a question about  CA-bicgstab method.I hope receive your reply.
I want to use CA-bicgstab methods with MPI parallel communication.However,I cant't find any communication statments in your code.
'CA' means 'communication avoiding'...
So,this code is written without any parallel communication,just serial?

**Comment by Rushsurf** [comment]
Thanks a lot !This issue has been fixed ,the answer is right...
And I have a question about CA-bicgstab method.I hope receive your reply.
I want to use CA-bicgstab methods with MPI parallel communication.However,I cant't find any communication statments in your code.
'CA' means 'communication avoiding'...
So,this code is written without any parallel communication,just serial?
